// Generated by CoffeeScript 2.3.2
(function() {
  //popups, contentscripts and background can interact with eachother by sending messages and setting storage
  var changeColor;

  changeColor = document.getElementById('changeColor');

  //data becomes an object with keys as properties
  //after we get the storage 'color', we call a function
  chrome.storage.sync.get('color', function(data) {
    changeColor.style.backgroundColor = data.color;
    //This sets up an attribute called value, used below
    return changeColor.setAttribute('value', data.color);
  });

  changeColor.onclick = function(element) {
    var color;
    color = element.target.value;
    return chrome.tabs.query({
      active: true,
      currentWindow: true
    }, function(tabs) {
      return chrome.tabs.executeScript(tabs[0].id, {
        code: 'document.body.style.backgroundColor = "' + color + '";'
      });
    });
  };

}).call(this);

//# sourceMappingURL=popup.js.map
