// Generated by CoffeeScript 2.3.2
//todo test this
var a, content, element, elements, i, jsonld, key, len, mark, node, root, src;

import 'elements';

import jsonldRdfaParser from 'jsonld-rdfa-parser';

jsonld = require('jsonld'); //todo maybe use required everywhere

//jsonldRdfaParser = require 'jsonld-rdfa-parser'
console.log('here');

src = 'C:\\Users\\Kanan-PC\\Desktop\\Lantern\\Example\\Example2.html';

content = null;

jsonld.registerRDFParser('text/html', jsonldRdfaParser);

jsonld.fromRDF(src, {
  format: 'text/html'
}, function(err, data) {
  return content = data;
});

elements = {};

mark = 0;

for (i = 0, len = content.length; i < len; i++) {
  element = content[i];
  //Skip declarations
  if (mark === 0) {
    mark = 1;
    continue;
  }
  node = addElement(element);
  if (node == null) {
    continue;
  }
  a = [node, 0];
  elements[node.id] = a;
}

//elements = {id: [node, 0]...}
for (key in elements) {
  element = elements[key][0];
  element.addChildren(elements);
}

root = new tree(elements);

elements = {
  elements: root.children,
  index: 0,
  notifications: []
};

chrome.storage.local.set({
  test: elements
});

//# sourceMappingURL=scraper.js.map
